### ISSUE TITLE
Add an Instance Scan for using GlideRecordSecure instead of GlideRecord API for Client Callable Script Includes

### ISSUE THREAD

**Issue by niamccash** [ServiceNowDevProgram/example-instancescan-checks#58]
As per https://docs.servicenow.com/bundle/utah-api-reference/page/script/server-scripting/concept/c_ScriptIncludes.html#title_client-callable-script-includes 

![image](https://github.com/ServiceNowDevProgram/example-instancescan-checks/assets/39105458/9c6682b5-9d12-4104-92a1-8310dba2f1f3)

**Comment by aman2519** [comment]
I can take this up

**Comment by aman2519** [comment]
@niamccash 
I think the issue was not assigned to me, could you please do that?
