### ISSUE TITLE
Add check for running Business Rules on Transform Maps

### ISSUE THREAD

**Issue by niamccash** [ServiceNowDevProgram/example-instancescan-checks#63]
See https://docs.servicenow.com/bundle/tokyo-platform-administration/page/administer/technical-best-practice/concept/c_TroubleshootImportSetPerformance.html

**Comment by smartcarleen** [comment]
I'll take this one, if @niamccash doesn't want it!

**Comment by niamccash** [comment]
Go for it @smartcarleen! All yours.

**Comment by aman2519** [comment]
Hi @smartcarleen 
If you haven't started, can I take this up?

**Comment by smartcarleen** [comment]
Sure @aman2519

**Comment by MartinStoyanoff** [comment]
@aman2519 it is all yous now :)
