### ISSUE TITLE
Add check for orphaned Catalog UI Policies

### ISSUE THREAD

**Issue by niamccash** [ServiceNowDevProgram/example-instancescan-checks#64]
Sometimes, when developing new Catalog Items/Record Producers, I find left over Catalog UI Policies that are not used anywhere - _**not**_ associated with a catalog item and also **_not_** associated with a variable set. These are unnecessary configurations that just create bloat in your system and it is likely best to not move these configurations to production.

An Instance Scan could flag them/find them so that you can remove them from your Update Set and clean them up.

Full example at: https://www.servicenow.com/community/developer-articles/instance-scan-orphaned-catalog-configurations-examples/ta-p/2302050

**Comment by smartcarleen** [comment]
@niamccash, it looks like you already did this somewhere. Are you sure you don't want to assign this one to yourself? If you don't, I'll take it.

**Comment by niamccash** [comment]
@smartcarleen I didn't see it in the Readme so it probably doesn't exist yet in this repo. Feel free to take it.

**Comment by smartcarleen** [comment]
@niamccash can you assign me to this issue?

**Comment by niamccash** [comment]
@smartcarleen ugh, you're right. That's my bad. The check exists but I didn't see the description of it in the readme. Seems the readme was borked and shows the wrong title: 

![image](https://github.com/ServiceNowDevProgram/example-instancescan-checks/assets/39105458/f6ef9493-14d0-4563-a275-3ddc6033b1f8)

I'll close this and open a new incident for fixing the readme.
