### ISSUE TITLE
Add check for valid Script Include name

### ISSUE THREAD

**Issue by niamccash** [ServiceNowDevProgram/example-instancescan-checks#66]
It seems possible to create a Script Include with an invalid name (eg. one with a space in the name) . Initially, the Script checker will complain about Javascript errors: 
![image](https://github.com/ServiceNowDevProgram/example-instancescan-checks/assets/39105458/83d86a04-548a-494c-ba1c-3b442931982f)

But it's possible to fix those errors, forget to fix the script name, and then save the record: 
![image](https://github.com/ServiceNowDevProgram/example-instancescan-checks/assets/39105458/7d59551f-488b-4371-a0a5-5edea090f0b6)

**Comment by designitsecure** [comment]
Hi, Is it ok if I work on this one?

**Comment by niamccash** [comment]
@designitsecure Go for it! If you submit a PR that solves this issue, you can tag it to automatically close the issue on merge - see https://github.com/ServiceNowDevProgram/Hacktoberfest/wiki/Reviewing-a-Pull-Request#auto-resolving-issues
