### ISSUE TITLE
Add check for getReference

### ISSUE THREAD

**Issue by designitsecure** [ServiceNowDevProgram/example-instancescan-checks#70]
getReference is considered against best practice since it can impact performance. See: [https://docs.servicenow.com/bundle/vancouver-api-reference/page/script/client-scripts/concept/client-script-best-practices.html](https://docs.servicenow.com/bundle/vancouver-api-reference/page/script/client-scripts/concept/client-script-best-practices.html)

Copied from link:
Note: GlideRecord and g_form.getReference() are also available for retrieving server information. However, these methods are no longer recommended due to their performance impact. Both methods retrieve all fields in the requested GlideRecord when most cases only require one field.

**Comment by designitsecure** [comment]
I would love to work on this one

**Comment by MartinStoyanoff** [comment]
@designitsecure why not assign it to yourself then?

**Comment by niamccash** [comment]
Closed by PR #72
