### ISSUE TITLE
Fix Readme for Delete Orphaned Catalog UI Policies

### ISSUE THREAD

**Issue by niamccash** [ServiceNowDevProgram/example-instancescan-checks#86]
The Readme file was updated incorrectly at some point. The heading and the description do not match.  Heading should be fixed to match the description of the check. See the headings just above this one for similar check description.

---
### Update set description should not be empty
Catalog UI policy should be used in either a Catalog Item or a Variable Set. Catalog UI Policies not in use should be deleted.

**Comment by NilotpalMaitra** [comment]
I will try to fix it

**Comment by NilotpalMaitra** [comment]
**Catalog UI policy should be used in either a Catalog Item or a Variable Set**
Validates that Catalog UI Policies are either associated with a Catalog Item or a Variable Set. Catalog UI Policies that are not in use should be deleted as they are unnecessary.


Is this fine?
