### ISSUE TITLE
Unable to use engine.current in Linter check

### ISSUE THREAD

**Issue by niamccash** [ServiceNowDevProgram/example-instancescan-checks#9]
App scoping issue - warning in the logs:

_java.lang.SecurityException: Method returned an object of type GlideRecord which is not allowed in scope x_appe_exa_checks
Caused by error in Linter Check: 'Linter check name here' at Line 4_

**Comment by phifogg** [comment]
This is unfortunately true, this check needs to run in global for now. The Scope restriction is being worked on for a future release.
